name: lovesync
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  socket_io_client: ^2.0.2
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  record: ^5.0.4
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4
  url_strategy: ^0.2.0

dependency_overrides:
  js: ^0.6.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/